name: Release j_notif binaries

on:
  push:
    branches:
      - master

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.29
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          ldflags: -extldflags -static -X github.com/chrislusf/seaweedfs/weed/util.COMMIT=${{github.sha}}
          extra_files: README.md config.example.yaml
          asset_name: "j_notif-${{ env.BUILD_TIME }}-${{ matrix.goos }}-${{ matrix.goarch }}"